### ISSUE TITLE
Give points to the people on certain autogroups.

### ISSUE THREAD

**Issue by carlos-osorio-developer** [phpBB-Studio/AdvancedPointsSystemAutoGroups#2]
Nice extension for the APS, it has so much potential. It is nice to have people into groups according to the points they have. 

But, how about making this work the other way around... Allowing the APS ext to give points to people on certain AutoGroup, on a daily basis or only when they enter the group. It should be nice to have this too.

This would allow the admin to give points to people that have reached a certain amount of time in the forum, or a certain amount of posts, or people that are active in the forum and have been logged in on the last 3 days, for example. 

Let's say I have a user that enters every day, with this feature I would be allowed to give him/her points daily if his/her last connection has been on the last 3 days.

I hope I could make myself clear. Thank you for these awesome extensions.

**Comment by 3D-I** [comment]
This extension only does:

    Unites the Advanced Points System and Auto Groups
    Enables a user’s points as a condition for Auto Groups
    Upon every points distribution, the condition will be checked 

Moreover, for support please use the forum, thanks.
